### ISSUE TITLE
Android: GameRequestDialog

### ISSUE THREAD

**Issue by MaximBelov** [MaximBelov/cordova-plugin-fbsdk#1]
from https://github.com/cordova-plugin-facebook-connect/cordova-plugin-facebook-connect/issues/119

@lossenorod

Hi, i recently switched from cordova-plugin-facebook-connect to your forked version cordova-plugin-fbsdk. I'm stuck on one issue with callbacks from GameRequestDialog that doesn't work on Android. I found out that this issue starts in FBSDK 12 and above. FBSDK 11.3 works properly. Do you have any idea maybe what can cause this? Thank you

**Comment by MaximBelov** [comment]
@lossenorod

You can try the test version
https://github.com/MaximBelov/cordova-plugin-fbsdk-lab/

Plugin changes:
https://github.com/MaximBelov/cordova-plugin-fbsdk/pull/2/files

1. package.json: update variables  for cordova-plugin-fbsdk
2. config.xml: update widget id
3. npm run build:android

**Comment by lossenorod** [comment]
@MaximBelov thank you very much for quick resopnse! Your answer did not fixed my issue but it gave me more insight inside my issue ( which was pretty simple to fix... ). I tried your project sample, it works properly with all callbacks for me. Cause of my issue was different. My project is made with Capacitor and is using cordova plugins. I tear down whole project to the scraps and used your sample and finally found the cause. The reason for not receiving these certain GameRequestDialog callbacks was because Capacitor itself is overwriting onActivityResult which is used by FB SDK since v12 to call back events. Thats why it was working properly in earlier versions and stopped after upgrade to v12. Anyways, thank you for your help!
